apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: reverseproxy1
  name: reverseproxy1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy1
    spec:
      containers:
      - image: dockertanj/simple-reverse-proxy1
        name: reverseproxy1
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


